export const RECEIVE_BUS_ROUTES = 'RECEIVE_BUS_ROUTES';

export const RECEIVE_BUS_ROUTE = 'RECEIVE_BUS_ROUTE';

export const RECEIVE_BUS_STOPS = 'RECEIVE_BUS_STOPS';

export const RECEIVE_BUS_STOP = 'RECEIVE_BUS_STOP';

export const RECEIVE_ARRIVALS = 'RECEIVE_ARRIVALS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
